### ISSUE TITLE
Implement Course Parser Professor Feature

### ISSUE THREAD

**Issue by Thaeriem** [Ryzon3/DegreeDoctor#19]

**Comment by crizbae** [comment]
@Thaeriem Is this asking for the implementation of something that adds professors to the course.json?

**Comment by Thaeriem** [comment]
> @Thaeriem Is this asking for the implementation of something that adds professors to the course.json?

Yes, this would probably be integrating an already generated dataset of courses and the professors who have taught it into the courses.json file (not actually implementing retrieving the professors themselves, that should be a separate issue).
