### ISSUE TITLE
Write pseudocode file for scraping routine

### ISSUE THREAD

**Issue by Ryzon3** [Ryzon3/DegreeDoctor#3]
In the backend we should create a file that documents the process of how we will go about scraping and assembling data then finally transforming into a usable output. This should be done before we start writing any code within the backend.

**Comment by Thaeriem** [comment]
I agree! Great issue Ryan!

**Comment by crizbae** [comment]
I agree! Let's get to work!

**Comment by Thaeriem** [comment]
> I agree! Let's get to work!

I'm excited as well, Chris!

**Comment by crizbae** [comment]
> > I agree! Let's get to work!
> 
> I'm excited as well, Chris!

Oh jeez!! All this talk is getting me pumped! Can't wait to get programming!
