### ISSUE TITLE
Add professor section to courses json file

### ISSUE THREAD

**Issue by crizbae** [Ryzon3/DegreeDoctor#32]
I can start filling the course json file with professor information with the sis-scraper, I just need that section to be added and for our current course json to be remade with it.

**Comment by Thaeriem** [comment]
> I can start filling the course json file with professor information with the sis-scraper, I just need that section to be added and for our current course json to be remade with it.

To clarify, do you simply need an "empty" json tag for professor information and you will inject it directly into courses.json? Or do you think it would be better to generate the data and then add it later. Perhaps it may be best to write a function that returns a dictionary of courses and professors that teach that course in a list as the value that courses.json can call from your sis scraper program.

**Comment by crizbae** [comment]
> > I can start filling the course json file with professor information with the sis-scraper, I just need that section to be added and for our current course json to be remade with it.
> 
> To clarify, do you simply need an "empty" json tag for professor information and you will inject it directly into courses.json? Or do you think it would be better to generate the data and then add it later. Perhaps it may be best to write a function that returns a dictionary of courses and professors that teach that course in a list as the value that courses.json can call from your sis scraper program.

Yeah just an empty json tag thats value is an empty list would be ideal I think. Right now(obviously can be changed to suit whatever our needs are) I store every professor for a given course in a list so it'd be easy to just dump that into the json.
