### ISSUE TITLE
Universalize json dump parameters 

### ISSUE THREAD

**Issue by crizbae** [Ryzon3/DegreeDoctor#41]
In our scrapers when we edit the json files we all do it differently so it ends up changing the formatting for each scraper. We should probably pick one style and stick with it for every scraper.

**Comment by Thaeriem** [comment]
Hello Chris, I am confused about the specifics: could you perhaps provide an example so we could talk through what exactly we need to standardize and maybe if we need to update our specs to match (is it the key-names, data entries etc?). Thanks - Yash

**Comment by crizbae** [comment]
Holly poggers! We have solved this issue!
