### ISSUE TITLE
Implement light/dark mode toggle using Quasar and fix styling issues.

### ISSUE THREAD

**Issue by liny18** [Ryzon3/DegreeDoctor#5]
Implement light/dark mode toggle using Quasar and fix styling issues.

**Comment by Thaeriem** [comment]
Just going to leave this here (https://dev.to/ananyaneogi/create-a-dark-light-mode-switch-with-css-variables-34l8) from a previous project but it should be easy to find many examples online for how to implement. Figure out whether you want a toggle switch (preferred prob) or a keybind? Also I know that the users default color scheme is stored on their browser so might want to look into that (I can crawl through my old project if needed just lmk).

**Comment by Ryzon3** [comment]
We will probably just use Quasar for this issue.
